erDiagram

    FORMULARIO ||--o{ ITEM : incluye
    ITEM ||--o{ ALTERNATIVA : ofrece
    FORMULARIO ||--o{ PARTICIPACION : genera
    PARTICIPACION ||--o{ SELECCION : registra
    ITEM ||--o{ SELECCION : corresponde

    FORMULARIO {
        string formulario_id PK
        string nombre
        string tema_principal
        string audiencia
        boolean disponible
    }

    ITEM {
        string item_id PK
        string pregunta_texto
        string formato
        boolean requerido
        string formulario_id FK
    }

    ALTERNATIVA {
        string alternativa_id PK
        string descripcion
        string item_id FK
    }

    PARTICIPACION {
        string participacion_id PK
        string usuario
        date fecha_envio
        string formulario_id FK
    }

    SELECCION {
        string seleccion_id PK
        string respuesta_marcada
        string item_id FK
        string participacion_id FK
    }